#!/bin/bash

#You can take the user input with read command and store it in a variable

read num
echo "$num"

echo "------------------------------------"

echo "what is your name:"
read name

echo "Enter the age:"
read age
