#!/bin/bash

#You can take the user input with read command and store it in a variable

read num
echo "$num"

read age
echo "Enter the age $age"

read name
echo "what is your name $name  "



read num
echo “The number is: $num”